version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www ## espace de stockage
      - ./docker/logs/nginx:/var/logs/nginx ## espace de stockage des logs nginx
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf # Configuration du nginx
    depends_on:
      - php
      - mysql
      - maildev
    networks:
      - lan

  mysql:
    build: 
      context: docker/mysql
      dockerfile: MySQL-5.6.Dockerfile
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - environment.yml
    networks:
      - lan

  php:
    image: leknoppix/php:php-8-0-3-simple
    user: 1000:985
    volumes:
      - ./app:/var/www ## espace de stockage
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - lan
    depends_on:
      - mysql
      - maildev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9092:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - lan

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "1026:25"
      - "1081:80"
    networks:
      - lan

  ftp:
    build:
      context: docker/vsftpd/
    ports:
      - 21:21
    volumes:
      - ./app:/home/dev/site/
    env_file:
      - environment.yml

  nodejs:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
    container_name: nodejs
    volumes:
      - ./app:/var/www

  codesniffer:
    image: jakzal/phpqa:php8.0-alpine
    volumes:
      - ./app:/project ## espace de stockage
      - ./docker/logs/tmp-phpqa:/tmp

volumes:
  mysql:

networks:
  lan: